# Praduman Pandey  19BCE0208

Implement Random forest Trees algorithm and test the algorithm using any data set of your choice. The output should include Accuracy, Error rate, Precision and recall rate along with the confusion matrix.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('car_evaluation.csv')

In [3]:
df.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   vhigh    1727 non-null   object
 1   vhigh.1  1727 non-null   object
 2   2        1727 non-null   object
 3   2.1      1727 non-null   object
 4   small    1727 non-null   object
 5   low      1727 non-null   object
 6   unacc    1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [5]:
df.isnull().sum()

vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [6]:
df.shape

(1727, 7)

In [7]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns=col_names

In [8]:
df['class'].value_counts()

unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64

In [9]:
x=df.drop('class',axis=1)
y=df['class']

In [10]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25)
xtrain.shape,ytrain.shape

((1295, 6), (1295,))

In [11]:
import category_encoders as ce
ec=ce.OrdinalEncoder(cols=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'])
xtrain=ec.fit_transform(xtrain)
xtest=ec.transform(xtest)

In [12]:
xtrain.head()

buying  maint  doors  persons  lug_boot  safety
1209       1      1      1        1         1       1
429        2      1      2        1         2       1
730        3      2      2        2         3       2
952        1      3      2        2         2       2
115        2      4      1        2         2       2

In [13]:
xtest.head()

buying  maint  doors  persons  lug_boot  safety
718       3      2      4        3         2       2
798       3      1      3        3         2       1
95        2      3      2        3         2       3
695       3      2      3        1         1       3
757       3      1      1        2         3       2

In [14]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier()
rfc.fit(xtrain,ytrain)

RandomForestClassifier()

In [15]:
ypred=rfc.predict(xtest)

from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,ypred))

0.9490740740740741


In [16]:
rfc50=RandomForestClassifier(n_estimators=50)

In [17]:
rfc50.fit(xtrain,ytrain)
ypred50=rfc50.predict(xtest)
print(accuracy_score(ytest,ypred50))

0.9444444444444444


In [18]:
rfc100=RandomForestClassifier(n_estimators=100)
rfc100.fit(xtrain,ytrain)
ypred100=rfc100.predict(xtest)
print(accuracy_score(ytest,ypred100))

0.9421296296296297


In [19]:
clf100=RandomForestClassifier(n_estimators=100)
clf100.fit(xtrain,ytrain)

fscores=pd.Series(clf100.feature_importances_, index=xtrain.columns)
fscores

buying      0.188722
maint       0.123578
doors       0.081640
persons     0.232737
lug_boot    0.091553
safety      0.281770
dtype: float64

In [20]:
xtrain2=xtrain.drop(['doors','lug_boot'],axis=1)
xtest2=xtest.drop(['doors','lug_boot'],axis=1)

rfc2=RandomForestClassifier(n_estimators=50)
rfc2.fit(xtrain2,ytrain)
ypred2=rfc2.predict(xtest2)
print(accuracy_score(ytest,ypred2))

0.8611111111111112


In [21]:
from sklearn.model_selection import train_test_split

x2 = df.drop(['class', 'doors'], axis=1)
y2 = df['class']

xtrain4,xtest4,ytrain4,ytest4=train_test_split(x2,y2,test_size=0.25)

import category_encoders as ce
ec2=ce.OrdinalEncoder(cols=['buying', 'maint', 'persons', 'lug_boot', 'safety'])
xtrain4=ec2.fit_transform(xtrain4)
xtest4=ec2.transform(xtest4)

clf2 = RandomForestClassifier()

#xtrain4.info()

clf2.fit(xtrain4, ytrain4)

ypred4 = clf2.predict(xtest4)

In [22]:
print(accuracy_score(ytest4,ypred4))

0.9513888888888888


In [23]:
clf3=RandomForestClassifier(n_estimators=50)
clf3.fit(xtrain4,ytrain4)
ypred5=clf3.predict(xtest4)
print(accuracy_score(ytest4,ypred5))

0.9513888888888888


In [24]:
from sklearn.metrics import classification_report
print(classification_report(ytest4,ypred4))

              precision    recall  f1-score   support

         acc       0.89      0.94      0.91       107
        good       0.83      0.88      0.86        17
       unacc       0.99      0.97      0.98       297
       vgood       0.86      0.55      0.67        11

    accuracy                           0.95       432
   macro avg       0.89      0.84      0.85       432
weighted avg       0.95      0.95      0.95       432



In [25]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ytest4,ypred4))

[[101   2   4   0]
 [  1  15   0   1]
 [  7   1 289   0]
 [  5   0   0   6]]
